language: node_js
node_js:
 - 8.10.0

before_install:
 - npm i -g serverless
 - npm i -g geckodriver
 - sls dynamodb install

install:
 - npm i

before_script:
 - 'sls offline start > /dev/null 2>&1 &'

script:
 - npm test
 - npm run integration

after_script:
 - 'kill $(pgrep -f sls)'
