language: node_js
node_js:
 - 8.10.0

# Setup xvfb for graphics in integration tests
dist: xenial
services:
  - xvfb

# Setup firefox headless addon
env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest

before_install:
 - npm i -g serverless
 - npm i -g geckodriver # Needed for firefox tests
 - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
 - mkdir geckodriver
 - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
 - export PATH=$PATH:$PWD/geckodriver
 - sls dynamodb install

install:
 - npm i

before_script:
 - 'sls offline start > slslog.txt 2>&1 &' # Startup the webserver

script:
 - npm test
 - npm run integration

after_script:
 - 'kill $(pgrep -f sls)' # Teardown the webserver
 - echo
 - cat slslog.txt # Display sls log
