language: node_js
node_js:
 - 12

# Setup xvfb for graphics in integration tests
dist: xenial
services:
  - xvfb

# Setup firefox headless addon
env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest

before_install:
 - npm i -g serverless
# Start geckodriver install
 - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
 - mkdir geckodriver
 - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
 - export PATH=$PATH:$PWD/geckodriver
# End geckodriver install

install:
 - npm i
 - sls dynamodb install

before_script:
 # Provide ssm variables for serverless offline in .env file
 - echo "domain-dev=dev.example.com\ncookieSecret=shhhh\ns3Bucket=$S3_BUCKET\nstorageBucket=$STORAGE\nsolrPort=8983\nsolrCore=example\nsolrSite=solr" > .env
 - 'sls offline start > slslog.txt 2>&1 &' # Startup the webserver
 - sleep 5s # Give time to startup

script:
 - npm test
# - npm run integration
 - npx mocha test/specs/issues-new.js

after_script:
 - 'kill $(pgrep -f sls)' # Teardown the webserver
 - cat slslog.txt # Display sls log
