language: node_js
node_js:
 - 8.10.0

before_install:
 - npm i -g serverless
 - npm i -g geckodriver
 - sls dynamodb install

install:
 - npm i

before_script:
 - sls offline start

script:
 - npm test
 - npm run integration
